/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlelab1;

import Graficos.TimeSeriesChart;
import Enum.TipoOnda;
import static Enum.TipoOnda.Degrau;
import static Enum.TipoOnda.Serra;
import Graficos.FuncaoTimeSeries;
import Graficos.NivelTimeSeries;
import Processadores.ControladorMalhaAberta;
import funcoes.Degrau;
import funcoes.Onda;
import funcoes.Quadrada;
import funcoes.Senoide;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JRadioButton;
import projetocontrole.dominio.Aleatoria;
import util.ConfiguracaoProjeto;
import util.InterfaceUtil;
import util.StringUtil;
import static java.lang.Thread.sleep;
import util.FabricaOnda;
import util.ThreadFactory;

/**
 *
 * @author lucasnobre
 */
public class Gui extends javax.swing.JFrame {

    TimeSeriesChart funcaoChart,nivelChart;
    TipoOnda tipo;
    ConfiguracaoProjeto cfg;

    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
        cfg = new ConfiguracaoProjeto();
        Component[] funcoes = seletorFuncaoPanel.getComponents();
        for (Component funcao : funcoes) {
            buttonGroup1.add((JRadioButton) funcao);
        }

        graficosPanel.setLayout(new GridLayout(1, 2));
        funcaoChart = new FuncaoTimeSeries("Função de Entrada", "Tensão (V)", "Tensao de Entrada");
        nivelChart = new NivelTimeSeries("Nivel Tanques", "Altura (cm)", "Nivel Tanque 1");
        funcaoPanel.add(funcaoChart);
        nivelPanel.add(nivelChart);

        nivelPanel.revalidate();
        nivelPanel.setLayout(new GridLayout(1, 1));
        nivelPanel.repaint();
        funcaoPanel.revalidate();
        funcaoPanel.setLayout(new GridLayout(1, 1));
        funcaoPanel.repaint();
        desabilitarCampos();
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        seletorFuncaoPanel = new javax.swing.JPanel();
        senoideRadioButton = new javax.swing.JRadioButton();
        quadradaRadioButton = new javax.swing.JRadioButton();
        denteSerraRadioButton = new javax.swing.JRadioButton();
        aleatoriaRadioButton = new javax.swing.JRadioButton();
        degrauRadioButton = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tipoOndaLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        amplitudeSlider = new javax.swing.JSlider();
        periodo = new javax.swing.JSpinner();
        tensaoMaxAle = new javax.swing.JSpinner();
        periodoMaxAle = new javax.swing.JSpinner();
        tensaoMinAle = new javax.swing.JSpinner();
        periodoMinAle = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        valorAmplitudeLabel = new javax.swing.JLabel();
        altura = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        offsetSpinner = new javax.swing.JSpinner();
        jButton3 = new javax.swing.JButton();
        graficosPanel = new javax.swing.JPanel();
        funcaoPanel = new javax.swing.JPanel();
        nivelPanel = new javax.swing.JPanel();
        malhaFechadaPanel = new javax.swing.JPanel();
        indicadorMalhaFechada = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuração"));

        seletorFuncaoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Função"));

        senoideRadioButton.setText("Senoide");
        senoideRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senoideRadioButtonActionPerformed(evt);
            }
        });

        quadradaRadioButton.setText("Quadrada");

        denteSerraRadioButton.setText("Serra");
        denteSerraRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denteSerraRadioButtonActionPerformed(evt);
            }
        });

        aleatoriaRadioButton.setText("Aleatória");

        degrauRadioButton.setText("Degrau");
        degrauRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degrauRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout seletorFuncaoPanelLayout = new javax.swing.GroupLayout(seletorFuncaoPanel);
        seletorFuncaoPanel.setLayout(seletorFuncaoPanelLayout);
        seletorFuncaoPanelLayout.setHorizontalGroup(
            seletorFuncaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seletorFuncaoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(seletorFuncaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(seletorFuncaoPanelLayout.createSequentialGroup()
                        .addComponent(degrauRadioButton)
                        .addGap(53, 53, 53)
                        .addGroup(seletorFuncaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(senoideRadioButton)
                            .addComponent(denteSerraRadioButton)))
                    .addComponent(quadradaRadioButton)
                    .addComponent(aleatoriaRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        seletorFuncaoPanelLayout.setVerticalGroup(
            seletorFuncaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seletorFuncaoPanelLayout.createSequentialGroup()
                .addGroup(seletorFuncaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(denteSerraRadioButton)
                    .addComponent(degrauRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(seletorFuncaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senoideRadioButton)
                    .addComponent(quadradaRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aleatoriaRadioButton)
                .addContainerGap())
        );

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Stop");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Parametros"));

        jLabel1.setText("Tipo da Onda  : ");

        jLabel3.setText("Amplitude (V) :");

        jLabel4.setText("Período (s)");

        amplitudeSlider.setMaximum(4);
        amplitudeSlider.setMinimum(-4);
        amplitudeSlider.setPaintLabels(true);
        amplitudeSlider.setPaintTicks(true);
        amplitudeSlider.setValue(0);
        amplitudeSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                amplitudeSliderMouseReleased(evt);
            }
        });

        periodo.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 0.5f));
        periodo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                periodoStateChanged(evt);
            }
        });

        tensaoMaxAle.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 0.5f));
        tensaoMaxAle.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tensaoMaxAledadosSinalGeradoChanged(evt);
            }
        });

        periodoMaxAle.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 0.5f));
        periodoMaxAle.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                periodoMaxAleStateChanged(evt);
            }
        });

        tensaoMinAle.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 0.5f));
        tensaoMinAle.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                stateChangedHandler(evt);
            }
        });

        periodoMinAle.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 0.5f));
        periodoMinAle.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                periodoMinAledadosSinalGeradoChanged(evt);
            }
        });

        jLabel5.setText("Tensão Max ");

        jLabel6.setText("Tensão Min");

        jLabel7.setText("Período Min");

        jLabel8.setText("Período Max");

        valorAmplitudeLabel.setText("0");

        altura.setModel(new javax.swing.SpinnerNumberModel(0, 0, 30, 1));

        jLabel2.setText("Altura (cm)");

        jLabel9.setText("OffSet (V)");

        offsetSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 0.5f));
        offsetSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                offsetSpinnerStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(amplitudeSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tipoOndaLabel))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tensaoMaxAle)
                                    .addComponent(periodoMaxAle))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                            .addComponent(tensaoMinAle)
                                            .addComponent(periodoMinAle)))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(valorAmplitudeLabel)
                                .addGap(51, 51, 51))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(periodo)
                                    .addComponent(altura))))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(34, 34, 34)
                            .addComponent(offsetSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tipoOndaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(valorAmplitudeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amplitudeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(offsetSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(periodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tensaoMaxAle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(34, 34, 34))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(tensaoMinAle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(periodoMinAle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(periodoMaxAle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jButton3.setText("Confirmar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        graficosPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Gráficos"));

        funcaoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Função"));

        javax.swing.GroupLayout funcaoPanelLayout = new javax.swing.GroupLayout(funcaoPanel);
        funcaoPanel.setLayout(funcaoPanelLayout);
        funcaoPanelLayout.setHorizontalGroup(
            funcaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        funcaoPanelLayout.setVerticalGroup(
            funcaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        nivelPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Nivel"));

        javax.swing.GroupLayout nivelPanelLayout = new javax.swing.GroupLayout(nivelPanel);
        nivelPanel.setLayout(nivelPanelLayout);
        nivelPanelLayout.setHorizontalGroup(
            nivelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        nivelPanelLayout.setVerticalGroup(
            nivelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout malhaFechadaPanelLayout = new javax.swing.GroupLayout(malhaFechadaPanel);
        malhaFechadaPanel.setLayout(malhaFechadaPanelLayout);
        malhaFechadaPanelLayout.setHorizontalGroup(
            malhaFechadaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
        );
        malhaFechadaPanelLayout.setVerticalGroup(
            malhaFechadaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout graficosPanelLayout = new javax.swing.GroupLayout(graficosPanel);
        graficosPanel.setLayout(graficosPanelLayout);
        graficosPanelLayout.setHorizontalGroup(
            graficosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graficosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(graficosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(funcaoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nivelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(graficosPanelLayout.createSequentialGroup()
                .addComponent(malhaFechadaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        graficosPanelLayout.setVerticalGroup(
            graficosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graficosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(funcaoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nivelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(malhaFechadaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        indicadorMalhaFechada.setText("Malha fechada");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seletorFuncaoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(indicadorMalhaFechada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(12, 12, 12))
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(13, 13, 13)))
                .addGap(18, 18, 18)
                .addComponent(graficosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(graficosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(seletorFuncaoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(indicadorMalhaFechada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Configuracao Rede");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void degrauRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degrauRadioButtonActionPerformed

    }//GEN-LAST:event_degrauRadioButtonActionPerformed

    private void senoideRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senoideRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senoideRadioButtonActionPerformed

    private void denteSerraRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_denteSerraRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_denteSerraRadioButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        iniciar();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String ondaString = InterfaceUtil.getSelectedButtonText(buttonGroup1);
        tipo = TipoOnda.valueOf(StringUtil.removerAcentos(ondaString));
        tipoOndaLabel.setText(ondaString);
        habilitarCampos(tipo);
        atualizarParametrosMalha();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void periodoMinAledadosSinalGeradoChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_periodoMinAledadosSinalGeradoChanged
        atualizarParametrosMalha();
    }//GEN-LAST:event_periodoMinAledadosSinalGeradoChanged

    private void tensaoMaxAledadosSinalGeradoChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tensaoMaxAledadosSinalGeradoChanged
        atualizarParametrosMalha();
    }//GEN-LAST:event_tensaoMaxAledadosSinalGeradoChanged

    private void amplitudeSliderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amplitudeSliderMouseReleased
        valorAmplitudeLabel.setText(Integer.toString(amplitudeSlider.getValue()));
        atualizarParametrosMalha();
    }//GEN-LAST:event_amplitudeSliderMouseReleased

    private void stateChangedHandler(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_stateChangedHandler
        atualizarParametrosMalha();
    }//GEN-LAST:event_stateChangedHandler

    private void periodoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_periodoStateChanged
        atualizarParametrosMalha();
    }//GEN-LAST:event_periodoStateChanged

    private void periodoMaxAleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_periodoMaxAleStateChanged
        atualizarParametrosMalha();
    }//GEN-LAST:event_periodoMaxAleStateChanged

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       new TelaConexaoConfig(cfg).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       cfg.setIsRunning(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void offsetSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_offsetSpinnerStateChanged
       atualizarParametrosMalha();
    }//GEN-LAST:event_offsetSpinnerStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aleatoriaRadioButton;
    private javax.swing.JSpinner altura;
    private javax.swing.JSlider amplitudeSlider;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton degrauRadioButton;
    private javax.swing.JRadioButton denteSerraRadioButton;
    private javax.swing.JPanel funcaoPanel;
    private javax.swing.JPanel graficosPanel;
    private javax.swing.JToggleButton indicadorMalhaFechada;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel malhaFechadaPanel;
    private javax.swing.JPanel nivelPanel;
    private javax.swing.JSpinner offsetSpinner;
    private javax.swing.JSpinner periodo;
    private javax.swing.JSpinner periodoMaxAle;
    private javax.swing.JSpinner periodoMinAle;
    private javax.swing.JRadioButton quadradaRadioButton;
    private javax.swing.JPanel seletorFuncaoPanel;
    private javax.swing.JRadioButton senoideRadioButton;
    private javax.swing.JSpinner tensaoMaxAle;
    private javax.swing.JSpinner tensaoMinAle;
    private javax.swing.JLabel tipoOndaLabel;
    private javax.swing.JLabel valorAmplitudeLabel;
    // End of variables declaration//GEN-END:variables

    private void habilitarCampos(TipoOnda tipo) {
        desabilitarCampos();
        
        if(indicadorMalhaFechada.isSelected()){
            altura.setEnabled(true);
            cfg.setTipoDeMalha("Fechada");
        }
        else{
            cfg.setTipoDeMalha("Aberta");
        }
        if (!tipo.equals(TipoOnda.Aleatoria)) {
            offsetSpinner.setEnabled(true);
            amplitudeSlider.setEnabled(true);
            if (!tipo.equals(TipoOnda.Degrau)) {
                periodo.setEnabled(true);
            }
        } 
        
        else {
            offsetSpinner.setEnabled(true);
            periodoMinAle.setEnabled(true);
            periodoMaxAle.setEnabled(true);
            tensaoMaxAle.setEnabled(true);
            tensaoMinAle.setEnabled(true);
        }
    }

    private void desabilitarCampos() {
        offsetSpinner.setEnabled(false);
        amplitudeSlider.setEnabled(false);
        tensaoMaxAle.setEnabled(false);
        tensaoMinAle.setEnabled(false);
        periodo.setEnabled(false);
        periodoMinAle.setEnabled(false);
        periodoMaxAle.setEnabled(false);
        altura.setEnabled(false);
    }

    private void atualizarParametrosMalha() {
        Double offset = Double.valueOf(this.offsetSpinner.getValue().toString());
        float periodo = Float.valueOf(this.periodo.getValue().toString());
        double tensaoMax = Double.valueOf(this.tensaoMaxAle.getValue().toString());
        double tensaoMin = Double.valueOf(this.tensaoMinAle.getValue().toString());
        float periodoMax = Float.valueOf(this.periodoMaxAle.getValue().toString());
        float periodoMin = Float.valueOf(this.periodoMinAle.getValue().toString());
        double tensaoMaxAle = Float.valueOf(this.periodoMaxAle.getValue().toString());
        cfg.setOffSet(offset);
        cfg.setAmplitude(new Double(amplitudeSlider.getValue()));
        cfg.setAmplitudeMax(tensaoMax);
        cfg.setAmplitudeMin(tensaoMin);
        cfg.setDuracaoMax(periodoMax);
        cfg.setDuracaoMin(periodoMin);
        cfg.setPeriodo(periodo);
        cfg.setTipoOnda(tipo);
        cfg.setAlturaDesejada( Double.valueOf(altura.getValue().toString()) );
        atualizaThreadControle(cfg);
        
        if(indicadorMalhaFechada.isSelected()){
            cfg.setAmplitudeMax(4.0);
        }
    }

    private void iniciar() {
        atualizarParametrosMalha();
        ControladorMalhaAberta controle = new ControladorMalhaAberta(cfg, funcaoChart, nivelChart);
        Thread controleThread = ThreadFactory.produzirThread(controle, "Controle");
        controleThread.start();
        System.out.println("ta rodando fi");
    }

    public void atualizaThreadControle(ConfiguracaoProjeto cfg) {
        Onda novaOnda = FabricaOnda.fabricarOnda(cfg);
        this.cfg.setOnda(novaOnda);
    }

}
