/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlelab1;

import Enum.TipoControlador;
import Enum.TipoMalha;
import Graficos.TimeSeriesChart;
import Enum.TipoOnda;
import static Enum.TipoOnda.Degrau;
import static Enum.TipoOnda.Serra;
import Graficos.FuncaoTimeSeries;
import Graficos.NivelTimeSeries;
import Processadores.Controlador;
import Processadores.ControladorMalhaAberta;
import funcoes.Degrau;
import funcoes.Onda;
import funcoes.Quadrada;
import funcoes.Senoide;
import funcoesControlador.FuncaoControle;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JRadioButton;
import projetocontrole.dominio.Aleatoria;
import util.ConfiguracaoProjeto;
import util.InterfaceUtil;
import util.StringUtil;
import static java.lang.Thread.sleep;
import util.FabricaControlador;
import util.FabricaFuncaoControlador;
import util.FabricaOnda;
import util.ThreadFactory;

/**
 *
 * @author lucasnobre
 */
public class Gui extends javax.swing.JFrame {

    TimeSeriesChart funcaoChart, nivelChart;
    TipoOnda tipoOnda;
    ConfiguracaoProjeto cfg;

    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
        cfg = new ConfiguracaoProjeto();
        Component[] funcoes = seletorFuncaoPanel.getComponents();
        for (Component funcao : funcoes) {
            buttonGroup1.add((JRadioButton) funcao);
        }

        this.leituraEsperadaLabel.setText("");
        this.leituraEsperadaEstaticaLabel.setText("");
        this.leituraSensorLabel.setText("");

        graficosPanel.setLayout(new GridLayout(1, 2));
        funcaoChart = new FuncaoTimeSeries("Função de Entrada", "Tensão (V)", "Tensao de Entrada");
        nivelChart = new NivelTimeSeries("Nivel Tanques", "Altura (cm)", "Nivel Tanque 1");
        funcaoChart.adicionarSerie("SetPoint");
        funcaoPanel.add(funcaoChart);
        nivelPanel.add(nivelChart);

        nivelPanel.revalidate();
        nivelPanel.setPreferredSize(new Dimension(50, 250));
        nivelPanel.setLayout(new GridLayout(1, 1));
        nivelPanel.repaint();
        funcaoPanel.revalidate();
        funcaoPanel.setLayout(new GridLayout(1, 1));
        funcaoPanel.repaint();
        desabilitarCampos();
        this.pack();
        this.setLocationRelativeTo(null);

        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        seletorFuncaoPanel = new javax.swing.JPanel();
        senoideRadioButton = new javax.swing.JRadioButton();
        quadradaRadioButton = new javax.swing.JRadioButton();
        denteSerraRadioButton = new javax.swing.JRadioButton();
        aleatoriaRadioButton = new javax.swing.JRadioButton();
        degrauRadioButton = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tipoOndaLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        amplitudeSlider = new javax.swing.JSlider();
        periodo = new javax.swing.JSpinner();
        tensaoMaxAle = new javax.swing.JSpinner();
        periodoMaxAle = new javax.swing.JSpinner();
        tensaoMinAle = new javax.swing.JSpinner();
        periodoMinAle = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        valorAmplitudeLabel = new javax.swing.JLabel();
        altura = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        offsetLabel = new javax.swing.JLabel();
        offsetSpinner = new javax.swing.JSpinner();
        spinnerKp = new javax.swing.JSpinner();
        spinnerKi = new javax.swing.JSpinner();
        spinnerKd = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        comboBoxControlador = new javax.swing.JComboBox<>();
        taoiSpinner = new javax.swing.JSpinner();
        taodSpinner = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        graficosPanel = new javax.swing.JPanel();
        funcaoPanel = new javax.swing.JPanel();
        nivelPanel = new javax.swing.JPanel();
        malhaFechadaSwitch = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        leituraSensorLabel = new javax.swing.JLabel();
        leituraEsperadaLabel = new javax.swing.JLabel();
        leituraEsperadaEstaticaLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuração"));

        seletorFuncaoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Função"));

        senoideRadioButton.setText("Senoide");
        senoideRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senoideRadioButtonActionPerformed(evt);
            }
        });

        quadradaRadioButton.setText("Quadrada");

        denteSerraRadioButton.setText("Serra");
        denteSerraRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denteSerraRadioButtonActionPerformed(evt);
            }
        });

        aleatoriaRadioButton.setText("Aleatória");

        degrauRadioButton.setText("Degrau");
        degrauRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degrauRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout seletorFuncaoPanelLayout = new javax.swing.GroupLayout(seletorFuncaoPanel);
        seletorFuncaoPanel.setLayout(seletorFuncaoPanelLayout);
        seletorFuncaoPanelLayout.setHorizontalGroup(
            seletorFuncaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seletorFuncaoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(seletorFuncaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(seletorFuncaoPanelLayout.createSequentialGroup()
                        .addComponent(degrauRadioButton)
                        .addGap(53, 53, 53)
                        .addGroup(seletorFuncaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(senoideRadioButton)
                            .addComponent(denteSerraRadioButton)))
                    .addComponent(quadradaRadioButton)
                    .addComponent(aleatoriaRadioButton))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        seletorFuncaoPanelLayout.setVerticalGroup(
            seletorFuncaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seletorFuncaoPanelLayout.createSequentialGroup()
                .addGroup(seletorFuncaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(denteSerraRadioButton)
                    .addComponent(degrauRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(seletorFuncaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senoideRadioButton)
                    .addComponent(quadradaRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aleatoriaRadioButton)
                .addContainerGap())
        );

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Stop");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Parametros"));

        jLabel1.setText("Tipo da Onda  : ");

        jLabel3.setText("Amplitude (V) :");

        jLabel4.setText("Período (s)");

        amplitudeSlider.setMaximum(4);
        amplitudeSlider.setMinimum(-4);
        amplitudeSlider.setPaintLabels(true);
        amplitudeSlider.setPaintTicks(true);
        amplitudeSlider.setValue(0);
        amplitudeSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                amplitudeSliderMouseReleased(evt);
            }
        });

        periodo.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 0.5f));
        periodo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                periodoStateChanged(evt);
            }
        });

        tensaoMaxAle.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 0.5f));
        tensaoMaxAle.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tensaoMaxAledadosSinalGeradoChanged(evt);
            }
        });

        periodoMaxAle.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 0.5f));
        periodoMaxAle.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                periodoMaxAleStateChanged(evt);
            }
        });

        tensaoMinAle.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 0.5f));
        tensaoMinAle.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                stateChangedHandler(evt);
            }
        });

        periodoMinAle.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 0.5f));
        periodoMinAle.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                periodoMinAledadosSinalGeradoChanged(evt);
            }
        });

        jLabel5.setText("Tensão Max ");

        jLabel6.setText("Tensão Min");

        jLabel7.setText("Período Min");

        jLabel8.setText("Período Max");

        valorAmplitudeLabel.setText("0");

        altura.setModel(new javax.swing.SpinnerNumberModel(0, 0, 30, 1));
        altura.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                alturaStateChanged(evt);
            }
        });

        jLabel2.setText("Altura (cm)");

        offsetLabel.setText("OffSet (V)");

        offsetSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 0.5f));
        offsetSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                offsetSpinnerStateChanged(evt);
            }
        });

        spinnerKp.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));
        spinnerKp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerKpStateChanged(evt);
            }
        });

        spinnerKi.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));
        spinnerKi.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerKiStateChanged(evt);
            }
        });

        spinnerKd.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));
        spinnerKd.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerKdStateChanged(evt);
            }
        });

        jLabel10.setText("Kp");

        jLabel11.setText("Ki");

        jLabel12.setText("Kd");

        jLabel13.setText("Tipo Controlador");

        comboBoxControlador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "P", "PI", "PD", "PID", "PI-D" }));
        comboBoxControlador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboBoxControladorMouseClicked(evt);
            }
        });
        comboBoxControlador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxControladorActionPerformed(evt);
            }
        });

        taoiSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));
        taoiSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                taoiSpinnerStateChanged(evt);
            }
        });

        taodSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));
        taodSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                taodSpinnerStateChanged(evt);
            }
        });

        jLabel14.setText("Ti");

        jLabel15.setText("Td");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(amplitudeSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(valorAmplitudeLabel)
                        .addGap(66, 66, 66))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoOndaLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(comboBoxControlador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel6)
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(periodoMaxAle, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tensaoMaxAle)
                        .addComponent(tensaoMinAle, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(offsetLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(offsetSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(periodoMinAle, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(altura)
                                        .addComponent(periodo))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(spinnerKp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spinnerKi)
                                    .addComponent(spinnerKd, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taoiSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taodSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tipoOndaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(valorAmplitudeLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(amplitudeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(comboBoxControlador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(offsetLabel)
                                    .addComponent(offsetSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(periodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(tensaoMinAle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tensaoMaxAle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(periodoMaxAle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2)
                        .addComponent(periodoMinAle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(taoiSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(taodSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerKp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerKi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerKd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton3.setText("Confirmar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        graficosPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Gráficos"));

        funcaoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Função"));

        javax.swing.GroupLayout funcaoPanelLayout = new javax.swing.GroupLayout(funcaoPanel);
        funcaoPanel.setLayout(funcaoPanelLayout);
        funcaoPanelLayout.setHorizontalGroup(
            funcaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        funcaoPanelLayout.setVerticalGroup(
            funcaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        nivelPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Nivel"));

        javax.swing.GroupLayout nivelPanelLayout = new javax.swing.GroupLayout(nivelPanel);
        nivelPanel.setLayout(nivelPanelLayout);
        nivelPanelLayout.setHorizontalGroup(
            nivelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 199, Short.MAX_VALUE)
        );
        nivelPanelLayout.setVerticalGroup(
            nivelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout graficosPanelLayout = new javax.swing.GroupLayout(graficosPanel);
        graficosPanel.setLayout(graficosPanelLayout);
        graficosPanelLayout.setHorizontalGroup(
            graficosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graficosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(graficosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nivelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(funcaoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        graficosPanelLayout.setVerticalGroup(
            graficosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graficosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(funcaoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nivelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        malhaFechadaSwitch.setText("Malha Fechada");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Leituras"));

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel9.setText("Leitura do Sensor Atual");

        leituraSensorLabel.setText("inicial");

        leituraEsperadaLabel.setText("inicial");

        leituraEsperadaEstaticaLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        leituraEsperadaEstaticaLabel.setText("Leitura Esperada do Sensor");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(leituraSensorLabel)
                .addGap(18, 18, 18)
                .addComponent(leituraEsperadaEstaticaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(leituraEsperadaLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel9)
                .addComponent(leituraSensorLabel)
                .addComponent(leituraEsperadaLabel)
                .addComponent(leituraEsperadaEstaticaLabel))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(malhaFechadaSwitch)
                                .addGap(144, 144, 144)
                                .addComponent(jButton3))
                            .addComponent(seletorFuncaoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(graficosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(123, 123, 123))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(graficosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(seletorFuncaoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(malhaFechadaSwitch))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1)))))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Configuracao Rede");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new TelaConexaoConfig(cfg).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String ondaString = InterfaceUtil.getSelectedButtonText(buttonGroup1);
        tipoOnda = TipoOnda.valueOf(StringUtil.removerAcentos(ondaString));
        habilitarCampos(tipoOnda);
        tipoOndaLabel.setText(ondaString);
        atualizarParametrosMalha();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void taodSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_taodSpinnerStateChanged
        Double taod = Double.valueOf(taodSpinner.getValue().toString());
        Double kp = Double.valueOf(spinnerKp.getValue().toString());
        spinnerKd.setValue(kp * taod);
        atualizarParametrosMalha();
    }//GEN-LAST:event_taodSpinnerStateChanged

    private void taoiSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_taoiSpinnerStateChanged
        Double taoi = Double.valueOf(taoiSpinner.getValue().toString());
        Double kp = Double.valueOf(spinnerKp.getValue().toString());
        spinnerKi.setValue(kp / taoi);
        atualizarParametrosMalha();
    }//GEN-LAST:event_taoiSpinnerStateChanged

    private void comboBoxControladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxControladorActionPerformed
        atualizarParametrosMalha();
    }//GEN-LAST:event_comboBoxControladorActionPerformed

    private void comboBoxControladorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboBoxControladorMouseClicked
        atualizarParametrosMalha();
    }//GEN-LAST:event_comboBoxControladorMouseClicked

    private void spinnerKdStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerKdStateChanged
        Double kd = Double.valueOf(spinnerKd.getValue().toString());
        Double kp = Double.valueOf(spinnerKp.getValue().toString());
        taodSpinner.setValue(kd / kp);
        atualizarParametrosMalha();
    }//GEN-LAST:event_spinnerKdStateChanged

    private void spinnerKiStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerKiStateChanged
        Double ki = Double.valueOf(spinnerKi.getValue().toString());
        Double kp = Double.valueOf(spinnerKp.getValue().toString());
        taoiSpinner.setValue(kp / ki);
        atualizarParametrosMalha();
    }//GEN-LAST:event_spinnerKiStateChanged

    private void spinnerKpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerKpStateChanged

        atualizarParametrosMalha();
    }//GEN-LAST:event_spinnerKpStateChanged

    private void offsetSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_offsetSpinnerStateChanged
        atualizarParametrosMalha();
    }//GEN-LAST:event_offsetSpinnerStateChanged

    private void alturaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_alturaStateChanged
        atualizarParametrosMalha();
    }//GEN-LAST:event_alturaStateChanged

    private void periodoMinAledadosSinalGeradoChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_periodoMinAledadosSinalGeradoChanged
        atualizarParametrosMalha();
    }//GEN-LAST:event_periodoMinAledadosSinalGeradoChanged

    private void stateChangedHandler(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_stateChangedHandler
        atualizarParametrosMalha();
    }//GEN-LAST:event_stateChangedHandler

    private void periodoMaxAleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_periodoMaxAleStateChanged
        atualizarParametrosMalha();
    }//GEN-LAST:event_periodoMaxAleStateChanged

    private void tensaoMaxAledadosSinalGeradoChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tensaoMaxAledadosSinalGeradoChanged
        atualizarParametrosMalha();
    }//GEN-LAST:event_tensaoMaxAledadosSinalGeradoChanged

    private void periodoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_periodoStateChanged
        atualizarParametrosMalha();
    }//GEN-LAST:event_periodoStateChanged

    private void amplitudeSliderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amplitudeSliderMouseReleased
        valorAmplitudeLabel.setText(Integer.toString(amplitudeSlider.getValue()));
        atualizarParametrosMalha();
    }//GEN-LAST:event_amplitudeSliderMouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cfg.setIsRunning(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        iniciar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void degrauRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degrauRadioButtonActionPerformed

    }//GEN-LAST:event_degrauRadioButtonActionPerformed

    private void denteSerraRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_denteSerraRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_denteSerraRadioButtonActionPerformed

    private void senoideRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senoideRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senoideRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aleatoriaRadioButton;
    private javax.swing.JSpinner altura;
    private javax.swing.JSlider amplitudeSlider;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboBoxControlador;
    private javax.swing.JRadioButton degrauRadioButton;
    private javax.swing.JRadioButton denteSerraRadioButton;
    private javax.swing.JPanel funcaoPanel;
    private javax.swing.JPanel graficosPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel leituraEsperadaEstaticaLabel;
    private javax.swing.JLabel leituraEsperadaLabel;
    private javax.swing.JLabel leituraSensorLabel;
    private javax.swing.JToggleButton malhaFechadaSwitch;
    private javax.swing.JPanel nivelPanel;
    private javax.swing.JLabel offsetLabel;
    private javax.swing.JSpinner offsetSpinner;
    private javax.swing.JSpinner periodo;
    private javax.swing.JSpinner periodoMaxAle;
    private javax.swing.JSpinner periodoMinAle;
    private javax.swing.JRadioButton quadradaRadioButton;
    private javax.swing.JPanel seletorFuncaoPanel;
    private javax.swing.JRadioButton senoideRadioButton;
    private javax.swing.JSpinner spinnerKd;
    private javax.swing.JSpinner spinnerKi;
    private javax.swing.JSpinner spinnerKp;
    private javax.swing.JSpinner taodSpinner;
    private javax.swing.JSpinner taoiSpinner;
    private javax.swing.JSpinner tensaoMaxAle;
    private javax.swing.JSpinner tensaoMinAle;
    private javax.swing.JLabel tipoOndaLabel;
    private javax.swing.JLabel valorAmplitudeLabel;
    // End of variables declaration//GEN-END:variables

    private void habilitarCampos(TipoOnda tipo) {
        desabilitarCampos();

        if (malhaFechadaSwitch.isSelected()) {
            altura.setEnabled(true);
            cfg.setTipoMalha(TipoMalha.Fechada);
            comboBoxControlador.setEnabled(true);
            if (!tipo.equals(TipoOnda.Aleatoria)) {
                offsetSpinner.setEnabled(true);
                if (!tipo.equals(TipoOnda.Degrau)) {
                    periodo.setEnabled(true);
                }
            } else {
                offsetSpinner.setEnabled(true);
                periodoMinAle.setEnabled(true);
                periodoMaxAle.setEnabled(true);
                tensaoMaxAle.setEnabled(true);
                tensaoMinAle.setEnabled(true);
            }
            spinnerKd.setEnabled(true);
        } else {
            if (!tipo.equals(TipoOnda.Aleatoria)) {
                offsetSpinner.setEnabled(true);
                amplitudeSlider.setEnabled(true);
                if (!tipo.equals(TipoOnda.Degrau)) {
                    periodo.setEnabled(true);
                }
            } else {
                offsetSpinner.setEnabled(true);
                periodoMinAle.setEnabled(true);
                periodoMaxAle.setEnabled(true);
                tensaoMaxAle.setEnabled(true);
                tensaoMinAle.setEnabled(true);
            }
            comboBoxControlador.setEnabled(false);
            cfg.setTipoMalha(TipoMalha.Aberta);
        }
    }

    private void desabilitarCampos() {
        desativarParametrosControle();
        comboBoxControlador.setEnabled(false);
        offsetSpinner.setEnabled(false);
        amplitudeSlider.setEnabled(false);
        tensaoMaxAle.setEnabled(false);
        tensaoMinAle.setEnabled(false);
        periodo.setEnabled(false);
        periodoMinAle.setEnabled(false);
        periodoMaxAle.setEnabled(false);
        altura.setEnabled(false);
    }

    private void atualizarParametrosMalha() {
        Double offset = Double.valueOf(this.offsetSpinner.getValue().toString());
        float periodo = Float.valueOf(this.periodo.getValue().toString());
        double tensaoMax = Double.valueOf(this.tensaoMaxAle.getValue().toString());
        double tensaoMin = Double.valueOf(this.tensaoMinAle.getValue().toString());
        float periodoMax = Float.valueOf(this.periodoMaxAle.getValue().toString());
        float periodoMin = Float.valueOf(this.periodoMinAle.getValue().toString());
        double tensaoMaxAle = Float.valueOf(this.periodoMaxAle.getValue().toString());
        double altura = Double.valueOf(this.altura.getValue().toString());
        double Kp = Double.valueOf(this.spinnerKp.getValue().toString());
        double Ki = Double.valueOf(this.spinnerKi.getValue().toString());
        double Kd = Double.valueOf(this.spinnerKd.getValue().toString());

        cfg.setOffSet(offset);
        if (cfg.getTipoMalha().equals(TipoMalha.Aberta)) {
            this.offsetLabel.setText("Offset (V)");
            this.leituraEsperadaLabel.setText("");
            this.leituraEsperadaEstaticaLabel.setText("");
            cfg.setAmplitude(new Double(amplitudeSlider.getValue()));
        } else if (cfg.getTipoMalha().equals(TipoMalha.Fechada)) {
            cfg.setAmplitude(altura + offset);
            this.offsetLabel.setText("Offset (cm)");
            this.leituraEsperadaLabel.setText("");
            this.leituraEsperadaEstaticaLabel.setText("Leitura Esperada do Sensor (cm)");
            cfg.setTipoControlador(TipoControlador.valorDe(String.valueOf(comboBoxControlador.getSelectedItem())));
        }
        cfg.setAmplitudeMax(tensaoMax);
        cfg.setAmplitudeMin(tensaoMin);
        cfg.setDuracaoMax(periodoMax);
        cfg.setDuracaoMin(periodoMin);

        cfg.setKp(Kp);
        cfg.setKi(Ki);
        cfg.setKd(Kd);
        cfg.setPeriodo(periodo);
        cfg.setTipoOnda(tipoOnda);
        atualizaThreadControle(cfg);
        atualizaParametrosControle(cfg);

    }

    private void iniciar() {
        atualizarParametrosMalha();
        Controlador c = FabricaControlador.gerarControlador(cfg, funcaoChart, nivelChart, leituraSensorLabel, leituraEsperadaLabel);
        Thread controleThread = ThreadFactory.produzirThread(c, "Controle");
        controleThread.start();
        System.out.println("ta rodando fi");
    }

    public void atualizaThreadControle(ConfiguracaoProjeto cfg) {
        Onda novaOnda = FabricaOnda.fabricarOnda(cfg);
        if (cfg.getTipoMalha().equals(TipoMalha.Fechada)) {
            FuncaoControle funcaoControle = FabricaFuncaoControlador.fabricarFuncaoControlador(cfg);
             this.cfg.setFuncoesControle(funcaoControle);
        }
        this.cfg.setOnda(novaOnda);
    }

    private void atualizaParametrosControle(ConfiguracaoProjeto cfg) {
        desativarParametrosControle();
        switch (cfg.getTipoControlador()) {
            case P:
                spinnerKp.setEnabled(true);
                break;
            case PD:
                spinnerKp.setEnabled(true);
                spinnerKd.setEnabled(true);
                taodSpinner.setEnabled(true);
                break;
            case PI:
                spinnerKp.setEnabled(true);
                spinnerKi.setEnabled(true);
                taoiSpinner.setEnabled(true);
                break;
            case PI_D:
            case PID:
                spinnerKp.setEnabled(true);
                spinnerKd.setEnabled(true);
                taodSpinner.setEnabled(true);
                spinnerKi.setEnabled(true);
                taoiSpinner.setEnabled(true);
                break;
            default:
                break;
        }
    }

    private void desativarParametrosControle() {
        taodSpinner.setEnabled(false);
        taoiSpinner.setEnabled(false);
        spinnerKi.setEnabled(false);
        spinnerKd.setEnabled(false);
        spinnerKp.setEnabled(false);
    }

}
